### ISSUE TITLE
import 'url-change-event' gives error while importing library in angular

### ISSUE THREAD

**Issue by yashijain1998** [jerrykingxyz/url-change-event#17]
While importing this library in angular using import statement, it gives the following error:
**'constructor', which lacks return-type annotation, implicitly has an 'any' return type. 
constructor(option: IOption)**

Following is the PR for solving this issue, please review
#16

**Comment by jerrykingxyz** [comment]
constructor return void is better than any, i fixed this bug in 0.1.3, thanks for the report
