### ISSUE TITLE
Class constructor Event cannot be invoked without 'new'

### ISSUE THREAD

**Issue by liaodehui1** [jerrykingxyz/url-change-event#23]
When I execute the test through jest, an error is reported here.

![image](https://user-images.githubusercontent.com/39728398/202629533-57b4b90f-162e-4dc9-b3eb-ccc33dfa408b.png)

Please see how to solve this problem. thanks!

Maybe you can try to upgrade the project dependencies.

**Comment by jerrykingxyz** [comment]
I fixed some unreasonable code, but not sure if this issue is fixed as well. Please try 0.1.6, if it is not fixed, please provide the steps to reproduce.

**Comment by liaodehui1** [comment]
The problem has been solved, thanks!
